trigger:
- main

stages:
- stage: Build
  displayName: Build and push production

  jobs:
    - deployment: VMDeploy
      displayName: web
      pool:
        vmImage: 'ubuntu-latest'
      environment:
        name: Production
        resourceType: VirtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
              - script: |
                  sudo -E /var/home/core/bin/az-login.sh
                  export TAG=$(tag) 
                  sudo -E env "PATH=$PATH" docker-compose -f /var/app/docker-compose.yml up -d