trigger:
- staging

stages:
- stage: Build
  displayName: Build and push stage

  jobs:
    - deployment: VMDeploy
      displayName: web
      pool:
        vmImage: 'ubuntu-latest'
      environment:
        name: Staging
        resourceType: VirtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
              - script: |
                  az acr login --name gliff
                  TAG=$(tag) docker-compose up -f /var/app/docker-compose.yml -d