trigger:
- staging

variables:
 - name: tag
   value: latest
   
stages:
- stage: Build
  displayName: Build and push stage

  jobs:
    - deployment: VMDeploy
      displayName: web
      pool:
        vmImage: 'ubuntu-latest'
      environment:
        name: Staging
        resourceType: VirtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
              - script: TAG=${{parameters.tag}} docker-compose up -d