trigger:
- staging

stages:
- stage: Build
  displayName: Build and push stage

  jobs:
    - deployment: VMDeploy
      displayName: web
      pool:
        vmImage: 'ubuntu-latest'
      environment:
        name: Staging
        resourceType: VirtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
              - script: |
                  sudo /var/home/core/bin/az-login.sh
                  TAG=$(tag) sudo docker-compose -f /var/app/docker-compose.yml up -d