name: Bespoke tier request
about: Request a bespoke package tier to be created for customers not paying through Stripe or with unique package specifications
title: "[ISODATE]: [CUSTOMER]"
labels: ["bespoke"]
assignees:
  - cooper667
  - ChasNelson1990
body:
  - type: input
    id: sales-owner
    attributes:
      label: Sales contact
      description: Who is the sales contact for this bespoke tier?
      placeholder: You should also add this person as an Assignee.
    validations:
      required: true
  - type: number
    id: number-team
    attributes:
      label: How many team members should this bespoke package have?
      value: 1
    validations:
      required: true
  - type: number
    id: number-collab
    attributes:
      label: How many collaborators should this bespoke package have?
      value: 2
    validations:
      required: true
  - type: number
    id: base-storage
    attributes:
      label: How much storage should this bespoke package have?
      value: 1000
    validations:
      required: true
  - type: textarea
    id: comments
    attributes:
      label: Any additional information?
  - type: checkboxes
    id: purchase-order
    attributes:
      label: Purchase Order
      options:
        - label: I confirm that this sale has been approved by a Director and a purchase order has been received by the sales team
          required: true
