# Generated by Django 3.1.4 on 2021-04-23 09:23

from django.db import migrations


def add_tiers(apps, schema_editor):
    Tier = apps.get_model("myauth", "Tier")

    for tier in ["COMMUNITY", "PRO", "TEAM", "ENTERPRISE"]:
        t = Tier(name=tier)
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_tiers)]
