# Generated by Django 3.1.4 on 2021-04-23 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_auto_20210423_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='stripe_plan_id',
        ),
        migrations.AddField(
            model_name='team',
            name='tier',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='myauth.tier'),
            preserve_default=False,
        ),
    ]
