# Generated by Django 3.1.4 on 2021-06-14 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0003_invite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="from_team",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="myauth.team"),
        ),
    ]
