# Generated by Django 3.1.4 on 2021-06-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0006_recovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauth.userprofile'),
        ),
    ]
