# Generated by Django 3.1.4 on 2021-07-09 13:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0007_auto_20210624_1553"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        max_length=43,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Not a valid UID", regex="^[a-zA-Z0-9\\-_]{20,}$"
                            )
                        ],
                    ),
                ),
                ("expiry_date", models.DateTimeField()),
                (
                    "user_profile",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="myauth.userprofile"),
                ),
            ],
        ),
    ]
