# Generated by Django 3.1.4 on 2021-07-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0008_auto_20210709_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accepted_terms_and_conditions',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
