# Generated by Django 3.1.4 on 2021-08-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0012_auto_20210803_0812"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_collaborator",
            field=models.BooleanField(default=False),
        ),
    ]
