# Generated by Django 3.1.4 on 2021-08-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0013_userprofile_is_collaborator"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="is_collaborator",
            field=models.BooleanField(default=False),
        ),
    ]
