# Generated by Django 3.1.4 on 2021-09-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0015_update_stripe_prices"),
        ("myauth", "0015_trustedservice"),
    ]

    operations = []
