# Generated by Craig 3.1.4 on 2021-10-20 09:23

from django.db import migrations
import os


def add_tiers(apps, schema_editor):
    Tier = apps.get_model("myauth", "Tier")

    if os.environ.get("DJANGO_SETTINGS_MODULE") == "server.settings.production":
        print("Running PRODUCTION migration")

        Tier(
            id=10001,
            name="ACACIA",
            base_user_limit=5,
            base_collaborator_limit=0,
            base_project_limit=None,
            base_storage_limit=10000,
            is_custom=True,
        ).save()

        Tier(
            id=10002,
            name="OCTAHEDRON",
            base_user_limit=5,
            base_collaborator_limit=50,
            base_project_limit=None,
            base_storage_limit=1000 * 1000,
            is_custom=True,
        ).save()
    else:
        print("Running NON-PRODUCTION migration")
        Tier(
            id=10001,
            name="CUSTOM TEST PLAN",
            base_user_limit=5,
            base_collaborator_limit=50,
            base_project_limit=None,
            base_storage_limit=1000 * 1000,
            is_custom=True,
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0023_auto_20211020_1000"),
    ]

    operations = [migrations.RunPython(add_tiers)]
