# Generated by Django 3.1.4 on 2021-11-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0024_add_custom_tiers_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='projects',
            field=models.IntegerField(null=True, verbose_name='Number of user projects'),
        ),
    ]
