# Generated by Craig 3.1.4 on 2021-11-23 10:59

from django.db import migrations
import os


def add_tiers(apps, schema_editor):
    Tier = apps.get_model("myauth", "Tier")

    if os.environ.get("DJANGO_SETTINGS_MODULE") == "server.settings.production":
        print("Running PRODUCTION migration")

        Tier(
            id=10003,
            name="South Tyneside and Sunderland NHS Foundation Trust",
            base_user_limit=5,
            base_collaborator_limit=5,
            base_project_limit=None,
            base_storage_limit=10000,
            is_custom=True,
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0024_add_custom_tiers_1"),
    ]

    operations = [migrations.RunPython(add_tiers)]
