# Generated by Django 3.1.4 on 2022-01-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0026_billing_trial_end_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billing",
            old_name="trial_end_date",
            new_name="trial_end",
        ),
        migrations.AddField(
            model_name="billing",
            name="trial_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
