# Generated by Django 3.1.4 on 2022-02-02 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0028_plugin_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trustedservice',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='trustedservice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trustedservice',
            name='products',
        ),
        migrations.RemoveField(
            model_name='trustedservice',
            name='team',
        ),
        migrations.RemoveField(
            model_name='trustedservice',
            name='type',
        ),
        migrations.RemoveField(
            model_name='trustedservice',
            name='url',
        ),
        migrations.AddField(
            model_name='trustedservice',
            name='plugin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myauth.plugin', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plugin',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='myauth.team'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='trustedservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
