# Generated by Craig 3.1.4 on 2022-03-01 10:49

from django.db import migrations
import os


def add_tiers(apps, schema_editor):
    Tier = apps.get_model("myauth", "Tier")

    if os.environ.get("DJANGO_SETTINGS_MODULE") == "server.settings.production":
        print("Running PRODUCTION migration")

        Tier(
            id=10004,
            name="P&G",
            base_user_limit=5,
            base_collaborator_limit=15,
            base_project_limit=None,
            base_storage_limit=100000,
            is_custom=True,
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0030_auto_20220202_1231"),
    ]

    operations = [migrations.RunPython(add_tiers)]
