# Generated by Django 3.1.4 on 2022-03-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0027_auto_20220125_1341'),
        ('myauth', '0031_p_g_custom_plan'),
    ]

    operations = [
    ]
