# Generated by Django 3.1.4 on 2022-03-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0032_merge_20220308_1431"),
    ]

    operations = [
        migrations.AddField(
            model_name="tier",
            name="custom_subscription_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
