# Generated by Craig 3.1.4 on 2022-04-20 14:12
import os
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0033_tier_custom_subscription_id"),
    ]

    if os.environ.get("DJANGO_SETTINGS_MODULE") == "server.settings.production":
        print("Running PRODUCTION migration")
        operations = [
            migrations.RunSQL(
                """
            UPDATE myauth_tier SET name = 'COMMUNITY',
                stripe_flat_price_id = 'price_1KqXmgFauXVlvS5wwnpD7rVK',
                base_project_limit = null
            WHERE id = 1;
        """
            )
        ]
    else:
        print("Running NON-PRODUCTION migration")
        operations = [
            migrations.RunSQL(
                """
            UPDATE myauth_tier SET name = 'COMMUNITY',
                stripe_flat_price_id = 'price_1KqUZrFauXVlvS5wFQLYuPHi',
                base_project_limit = null
            WHERE id = 1;
        """
            )
        ]
