# Generated by Django 3.1.4 on 2022-06-29 09:35

from django.db import migrations, models


def add_default_author(apps, schema_editor):
    Plugin = apps.get_model("myauth", "Plugin")
    for plugin in Plugin.objects.all():
        plugin.author = plugin.team.name
        plugin.save()


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0036_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugin",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="plugin",
            name="author",
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
        migrations.RunPython(add_default_author),
        migrations.AlterField(
            model_name="plugin",
            name="author",
            field=models.CharField(max_length=50),
        ),
    ]
