# Generated by Django 3.1.4 on 2022-07-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0036_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(4, 'excellent'), (3, 'very good'), (2, 'good'), (1, 'fair'), (0, 'poor')])),
                ('comment', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
