# Generated by Django 3.1.4 on 2022-07-06 11:30

from django.db import migrations, models
import django.db.models.deletion


def add_default_origin(apps, schema_editor):
    Plugin = apps.get_model("myauth", "Plugin")
    for plugin in Plugin.objects.all():
        plugin.origin_id = plugin.id
        plugin.save()


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0037_plugin_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plugin",
            name="author",
        ),
        migrations.AddField(
            model_name="plugin",
            name="origin",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="myauth.plugin"
            ),
        ),
        migrations.RunPython(add_default_origin),
    ]
