# Generated by Django 3.1.4 on 2022-07-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0038_auto_20220706_1130"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugin",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trustedservice",
            name="encrypted_access_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trustedservice",
            name="public_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
