# Generated by Django 3.1.4 on 2022-07-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0039_auto_20220707_1016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plugin",
            name="is_public",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
