name: Build, Publish and Deploy store-staging-gliff

on:
  push:
    branches:
      - staging
      - azure-pipelines

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          with:
            submodules: true
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.v2_AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.v2_REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.v2_REGISTRY_USERNAME }}
            password: ${{ secrets.v2_REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.v2_REGISTRY_LOGIN_SERVER }}/store:${{ github.sha }}
            docker push ${{ secrets.v2_REGISTRY_LOGIN_SERVER }}/store:${{ github.sha }}
