name: lint and format
on:
  pull_request:
    types: [opened, edited, synchronize, auto_merge_enabled, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: black and flake8
        uses: ricardochaves/python-lint@v1.4.0
        with:
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: true
          use-mypy: false
          use-isort: false
