name: lint and fomat
on: push

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: install pipenv
        run: pip install pipenv
      - name: install dependencies
        run: pipenv sync --dev
      - name: format with black
        run: pipenv run black --verbose --diff .
  lint:
    needs: format
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: install pipenv
        run: pip install pipenv
      - name: install dependencies
        run: pipenv sync --dev
      - name: lint with flake8
        run: pipenv run lint
