# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - store-production-gliff(Production), Build and deploy Python app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Copy package tools
      run: |
        cp -r package_tools/* etebase-server/

    - name: Build using AppService-Build
      uses: azure/appservice-build@v2


    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: store-production-gliff
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AC7788FA9E04415F8ABDE9E7545AFABD }}

